import React, { useState, ReactNode } from 'react';
import { LanguageContext } from './hooks/useLanguage';

export type Language = 'en' | 'hi' | 'bn' | 'ta' | 'te' | 'mr' | 'gu' | 'kn' | 'ml' | 'or' | 'pa' | 'as' | 'ur';

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return getTranslation(key, language);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translation function
const getTranslation = (key: string, lang: Language): string => {
  const translations = getTranslations();
  // translations is typed as a generic map so we can index by any language code
  return (translations[lang as string]?.[key] as string) || (translations['en']?.[key] as string) || key;
};

// Translation data
const getTranslations = (): Record<string, Record<string, string>> => {
  return {
    en: {
      // Navigation
      'nav.modules': 'Training Modules',
      'nav.vr': 'VR Training',
      'nav.admin': 'Admin',
      'nav.logout': 'Logout',
      'nav.menu': 'Menu',
      'nav.darkMode': 'Dark Mode',
      
      // Login Page
      'login.title': 'DPRES Login',
      'login.subtitle': 'Disaster Preparedness & Response Education System',
      'login.madeInIndia': 'Made in India',
      'login.welcome': 'Welcome to DPRES!',
      'login.selectType': 'Please select your login type to continue',
      'login.student': 'Student Login',
      'login.studentDesc': 'Access learning modules and training',
      'login.admin': 'Admin Login',
      'login.adminDesc': 'Coming soon - Institutional management',
      'login.continue': 'Continue',
      'login.back': 'Back',
      'login.selectInstitution': 'Select Institution Type',
      'login.institutionQuestion': 'Are you studying in a school or college?',
      'login.school': 'School',
      'login.schoolDesc': 'Classes 6-12, Age 10-18',
      'login.college': 'College/University',
      'login.collegeDesc': 'Undergraduate/Graduate programs',
      'login.enterDetails': 'Enter Your Details',
      'login.provideInfo': 'Please provide your',
      'login.selectSchool': 'Select Your School',
      'login.selectCollege': 'Select Your College',
      'login.chooseSchool': 'Choose your school',
      'login.chooseCollege': 'Choose your college',
      'login.schoolCode': 'School Code',
      'login.collegeCode': 'College Code',
      'login.age': 'Age',
      'login.fullName': 'Full Name',
      'login.enterAge': 'Enter age',
      'login.enterName': 'Enter your full name',
      'login.enterHub': 'Enter Preparedness Hub',
      'login.buildingSafety': 'Building a safer tomorrow through education',
      'login.poweredBy': 'Powered by',
      'login.step1': 'Step 1: Select User Type',
      'login.step2': 'Step 2: Select Institution Type',
      'login.step3': 'Step 3: Enter Details',
      
      // Landing Page
      'landing.hero.title': 'Building Resilient Communities Through Education',
      'landing.hero.subtitle': 'Comprehensive disaster preparedness training for schools and colleges across India',
      'landing.hero.getStarted': 'Get Started',
      'landing.hero.learnMore': 'Learn More',
      'landing.quickAccess': 'Quick Access',
      'landing.emergency': 'Emergency',
      'landing.sos': 'SOS Alert',
      'landing.contacts': 'Quick Contacts',
      'landing.report': 'Report Incident',
      'landing.features.title': 'Comprehensive Disaster Preparedness Platform',
      'landing.features.subtitle': 'Empowering educational institutions with real-time alerts, interactive training modules, and immersive VR experiences for effective disaster response.',
      'landing.features.training': 'Training Modules',
      'landing.features.trainingDesc': 'Comprehensive disaster management training with interactive content and progress tracking.',
      'landing.features.vr': 'VR Training',
      'landing.features.vrDesc': 'Immersive virtual reality simulations for earthquake, fire, and other emergency scenarios.',
      'landing.features.realtime': 'Real-time Alerts',
      'landing.features.realtimeDesc': 'Region-specific disaster alerts and emergency notifications delivered instantly to your institution.',
      'landing.features.progress': 'Admin Oversight',
      'landing.features.progressDesc': 'Comprehensive monitoring and reporting tools for authorities and educational administrators.',
      'landing.stats.title': 'Impact Statistics',
      'landing.stats.students': 'Students Trained',
      'landing.stats.institutions': 'Institutions',
      'landing.stats.modules': 'Training Modules',
      'landing.stats.satisfaction': 'Satisfaction Rate',
      'landing.disasters.title': 'Recent Disasters & Case Studies',
      'landing.disasters.subtitle': 'Learn from real disasters that affected educational institutions and how proper preparedness saved lives',
      'landing.disasters.cyclone': 'Cyclone',
      'landing.disasters.flood': 'Flood',
      'landing.disasters.earthquake': 'Earthquake',
      'landing.disasters.wildfire': 'Wildfire',
      'landing.disasters.cycloneEmergency': 'Cyclone Emergency',
      'landing.disasters.floodEmergency': 'Flood Emergency',
      'landing.disasters.majorEarthquake': 'Major Earthquake',
      'landing.disasters.tsunamiEmergency': 'Tsunami Emergency',
      'landing.disasters.studentsAffected': 'Students Affected',
      'landing.disasters.studentsEvacuated': 'Students Evacuated Safely',
      'landing.disasters.studentsRelocated': 'Students Relocated',
      'landing.disasters.studentsRescued': 'Students Rescued',
      'landing.disasters.learnMore': 'Learn more about this disaster',
      'landing.disasters.cycloneFani': 'Cyclone Fani 2019',
      'landing.disasters.cycloneFaniDesc': 'Category 4 Super Cyclone • Odisha, India',
      'landing.disasters.cycloneFaniText': 'Early warning systems and school evacuation drills saved thousands of students. 156 schools used as relief centers.',
      'landing.disasters.punjabFloods': 'Punjab Floods 2023',
      'landing.disasters.punjabFloodsDesc': 'Monsoon Flooding • Punjab, India',
      'landing.disasters.punjabFloodsText': 'Swift action by school authorities and community preparedness ensured 99% of students reached safety. 89 schools served as temporary shelters.',
      'landing.disasters.gujarateEarthquake': 'Gujarat Earthquake 2001',
      'landing.disasters.gujarateEarthquakeDesc': '7.7 Magnitude • Gujarat, India',
      'landing.disasters.gujarateEarthquakeText': 'This disaster led to India\'s first comprehensive school safety guidelines. Drop, Cover, Hold drills became mandatory nationwide.',
      'landing.disasters.indianOceanTsunami': 'Indian Ocean Tsunami 2004',
      'landing.disasters.indianOceanTsunamiDesc': '9.1 Earthquake & Tsunami • Tamil Nadu Coasts',
      'landing.disasters.indianOceanTsunamiText': 'Led to India\'s coastal early warning systems. Schools in Chennai now have tsunami evacuation protocols and regular drills.',
      'landing.disasters.buildPreparedness': 'Ready to Build Your School\'s Disaster Preparedness?',
      'landing.disasters.joinInstitutions': 'Join thousands of institutions that have improved their emergency response through DPRES training',
      'landing.disasters.startTraining': 'Start Emergency Training Now',
      
      // Dashboard
      'dashboard.welcome': 'Welcome to Your Dashboard',
      'dashboard.overview': 'Overview',
      'dashboard.alerts.title': 'Emergency Alerts',
      'dashboard.alerts.noAlerts': 'No active alerts in your area',
      'dashboard.alerts.checkback': 'We\'ll notify you of any emergency situations',
      'dashboard.progress.title': 'Training Progress',
      'dashboard.progress.overall': 'Overall Progress',
      'dashboard.progress.modules': 'Modules Completed',
      'dashboard.progress.certificates': 'Certificates Earned',
      'dashboard.progress.hours': 'Training Hours',
  'dashboard.quickActions': 'Quick Actions',
  'dashboard.startTraining': 'Start Training',
  'dashboard.viewCertificates': 'View Certificates',
  'dashboard.emergencyKit': 'Emergency Kit',
  'dashboard.practiceQuiz': 'Practice Quiz',
      'dashboard.completedModule': 'Completed',
      'dashboard.earnedCertificate': 'Earned certificate in',
      'dashboard.startedModule': 'Started',
      'dashboard.viewAll': 'View All',
      'dashboard.alerts.description': 'Region-specific disaster alerts and notifications',
      'dashboard.sos.success': 'SOS Alert sent to nearest disaster authority.',
      'dashboard.sos.confirm': 'Emergency SOS',
      'dashboard.sos.description': 'Are you sure you want to trigger SOS? This will alert the nearest disaster management authorities.',
      'dashboard.sos.confirmButton': 'Confirm SOS',
      'dashboard.incident.success': 'Incident Report Sent Successfully.',
      'dashboard.learningProgress': 'Learning Progress',
  'dashboard.progressDesc': 'Your disaster preparedness training progress',
  'dashboard.modulesCompleted': 'Modules Completed',
  'dashboard.vrTrainingsCompleted': 'VR Trainings Completed',
  'dashboard.latestQuizScore': 'Latest Quiz Score',
      'dashboard.keepProgress': 'Great job! Keep up the progress',
      'dashboard.hoursAgo': 'hour ago',
      'dashboard.heavyRainfall': 'Heavy Rainfall',
      'dashboard.earthquakeTremors': 'Earthquake Tremors',
      'dashboard.alert': 'Alert',
      'dashboard.regionSpecific': 'Region-specific disaster alerts and notifications',
      'dashboard.moderateRainfall': 'Moderate to heavy rainfall expected in your region. Review flood preparedness protocols.',
      'dashboard.minorSeismic': 'Minor seismic activity detected. Stay alert and review earthquake safety procedures.',
      'dashboard.emergencyResponse': 'Emergency Response',
      'dashboard.moduleCompleted': 'Module 4 completed – Emergency Response',
      'dashboard.chennaiDistrict': 'Chennai District',
      'dashboard.tamilNaduRegion': 'Tamil Nadu Region',
      'dashboard.alerts.heavyRainfall': 'Heavy Rainfall Alert',
      'dashboard.alerts.earthquakeTremors': 'Earthquake Tremors Alert',
      'dashboard.alerts.rainfallDesc': 'Moderate to heavy rainfall expected in your region. Review flood preparedness protocols.',
      'dashboard.alerts.seismicDesc': 'Minor seismic activity detected. Stay alert and review earthquake safety procedures.',
      'dashboard.alerts.timeAgo2h': '2 hours ago',
      'dashboard.alerts.timeAgo6h': '6 hours ago',
      'dashboard.alerts.chennaiDistrict': 'Chennai District',
  'dashboard.quickAccess.title': 'Quick Access',
      'dashboard.quickAccess.description': 'Frequently used tools and resources',
      'dashboard.quickAccess.safetyProtocols': 'Safety Protocols',
      'dashboard.quickAccess.evacuationRoutes': 'Evacuation Routes',
      'dashboard.quickAccess.emergencyDirectory': 'Emergency Directory',
      'dashboard.quickAccess.incidentReports': 'Incident Reports',
      'dashboard.emergencyContacts': 'Emergency Contacts',
      'dashboard.emergencyContacts.fire': 'Fire Department',
      'dashboard.emergencyContacts.police': 'Police',
      'dashboard.emergencyContacts.medical': 'Medical Emergency',
      'dashboard.emergencyContacts.disaster': 'Disaster Management',
      'dashboard.emergencyContacts.tapToCall': 'Quick access to emergency services. Tap to call immediately.',
      'dashboard.emergencyContacts.call': 'Call',
      'dashboard.recentActivity': 'Recent Activity',
      'dashboard.recentActivityDesc': 'Your latest learning updates',
      'dashboard.recentActivity.module4': 'Module 4 completed – Emergency Response',
      'dashboard.recentActivity.vrFire': 'VR Fire Drill completed',
      'dashboard.recentActivity.evacuationTime': 'Evacuation time: 3 minutes 45 seconds',
      'dashboard.recentActivity.quizEarthquake': 'Quiz on Earthquake Safety scored 85%',
      'dashboard.recentActivity.performance': 'Above average performance!',
      'dashboard.recentActivity.keepProgress': 'Great job! Keep up the progress',
      'dashboard.recentActivity.timeAgo1h': '1 hour ago',
      'dashboard.recentActivity.timeAgo2d': '2 days ago',
      'dashboard.recentActivity.timeAgo3d': '3 days ago',
      'dashboard.incident.title': 'Report Incident',
      'dashboard.incident.description': 'Provide details about the incident you want to report.',
      'dashboard.incident.type': 'Type of Incident',
      'dashboard.incident.selectType': 'Select incident type',
      'dashboard.incident.fire': '🔥 Fire',
      'dashboard.incident.earthquake': '🌍 Earthquake',
      'dashboard.incident.medical': '🚑 Medical Emergency',
      'dashboard.incident.other': '⚠️ Other',
      'dashboard.incident.location': 'Location',
      'dashboard.incident.locationPlaceholder': 'Enter location details',
      'dashboard.incident.descriptionLabel': 'Short Description',
      'dashboard.incident.descriptionPlaceholder': 'Briefly describe the incident',
      'dashboard.incident.submit': 'Submit Report',
      
      // Modules Page
      'modules.title': 'Training Modules',
      'modules.subtitle': 'Master disaster preparedness through progressive learning phases',
      'modules.journey': 'Your Preparedness Journey',
      'modules.yourProgress': 'Your Progress',
      'modules.schoolAverage': 'Your School Average',
      'modules.collegeAverage': 'Your College Average',
      'modules.friendComparison': 'Friend Comparison',
      'modules.overall': 'Overall',
      'modules.modules': 'Modules',
      'modules.vrTrainings': 'VR Trainings',
      'modules.quizAverage': 'Quiz Average',
      'modules.school': 'School',
      'modules.college': 'College',
      'modules.selectFriend': 'Select a friend to compare',
      'modules.progress': 'Progress',
      'modules.duration': 'Duration',
      'modules.students': 'students',
      'modules.keyTopics': 'Key Topics',
      'modules.reviewModule': 'Review Module',
      'modules.continueLearning': 'Continue Learning',
      'modules.completePrevious': 'Complete Previous Modules',
      'modules.additionalResources': 'Additional Resources',
      'modules.resourcesDesc': 'Supplementary materials and references',
      'modules.resourceLibrary': 'Resource Library',
      'modules.bestPractices': 'Best Practices',
      'modules.caseStudies': 'Case Studies',
      'modules.completed': 'Completed',
      'modules.inProgress': 'In Progress',
      'modules.locked': 'Locked',
      'modules.aheadOfAverage': 'Amazing! You\'re ahead of your school average! 🚀',
      'modules.catchingUp': 'Almost there! You\'re catching up fast! 💪',
      'modules.keepGoing': 'Keep going! Every step counts! 🌟',
      'modules.yourSchool': 'Your School',
      'modules.yourCollege': 'Your College',
      'modules.aheadOfFriend': 'You\'re {percent}% ahead! 🎉',
      'modules.behindFriend': 'You\'re {percent}% behind. Keep going! 💪',
      'modules.minutesShort': 'min',
      'modules.video': 'Video',
      'modules.interactive': 'Interactive',
      'modules.mixed': 'Mixed',
      'modules.simulation': 'Simulation',
      
      // VR Training Page
      'vr.title': 'Virtual Reality Training',
      'vr.subtitle': 'Immersive disaster preparedness simulations using mobile VR',
      'vr.gettingStarted': 'Getting Started with Mobile VR Training',
      'vr.setupDesc': 'Use your smartphone and a cardboard VR viewer for immersive training',
      'vr.smartphone': 'Smartphone',
      'vr.smartphoneDesc': 'Android 6.0+ or iOS 10+ with gyroscope sensor',
      'vr.cardboardViewer': 'Cardboard VR Viewer',
      'vr.cardboardDesc': 'DIY cardboard or Google Cardboard compatible viewer',
      'vr.headphones': 'Headphones',
      'vr.headphonesDesc': 'Optional earphones for better immersion',
      'vr.downloadApp': 'Download VR App',
      'vr.setupGuide': 'Setup Guide',
      'vr.qrCodeDesc': 'Scan this QR code with your phone to download the DPRES VR app',
      'vr.comingSoon': 'Coming Soon',
      'vr.available': 'Available',
      'vr.beginner': 'Beginner',
      'vr.intermediate': 'Intermediate',
      'vr.advanced': 'Advanced',
      'vr.startTraining': 'Start VR Training',
      'vr.totalSessions': 'Total VR Sessions',
      'vr.completionRate': 'Completion Rate',
      'vr.avgSessionTime': 'Avg. Session Time',
      'vr.avgTime': '18 min',
      'vr.userRating': 'User Rating',
      'vr.trainingPreview': 'VR Training Preview',
      'vr.previewDesc': 'Experience a sample of our immersive training environment',
      'vr.previewEnvironment': 'Preview VR Environment',
      'vr.trainingEnvironmentAlt': 'VR Training Environment',
      'vr.earthquakeResponse': 'Earthquake Response',
      'vr.earthquakeDesc': 'Experience realistic earthquake scenarios and learn proper drop, cover, and hold techniques in a safe virtual environment.',
      'vr.fireEmergency': 'Fire Emergency',
      'vr.fireDesc': 'Navigate through fire emergency scenarios, practice evacuation routes, and learn proper use of fire safety equipment.',
      'vr.floodResponse': 'Flood Response',
      'vr.floodDesc': 'Learn flood safety protocols and evacuation procedures in various flooding scenarios and environments.',
      'vr.cyclonePreparedness': 'Cyclone Preparedness',
      'vr.cycloneDesc': 'Experience severe weather conditions and learn proper sheltering and safety measures during cyclonic storms.',
      'vr.duration15to20': '15-20 min',
      'vr.duration12to18': '12-18 min',
      'vr.duration20to25': '20-25 min',
      'vr.duration18to22': '18-22 min',
      
      // Common
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.cancel': 'Cancel',
      'common.save': 'Save',
      'common.edit': 'Edit',
      'common.delete': 'Delete',
      'common.view': 'View',
      'common.close': 'Close',
    },
    hi: {
      // Navigation
      'nav.dashboard': 'डैशबोर्ड',
      'nav.modules': 'प्रशिक्षण मॉड्यूल',
      'nav.vr': 'वीआर प्रशिक्षण',
      'nav.admin': 'एडमिन',
      'nav.logout': 'लॉगआउट',
      'nav.menu': 'मेनू',
      'nav.darkMode': 'डार्क मोड',
      
      // Login Page
      'login.title': 'डीपीआरईएस लॉगिन',
      'login.subtitle': 'आपदा तैयारी और प्रतिक्रिया शिक्षा प्रणाली',
      'login.madeInIndia': 'मेड इन इंडिया',
      'login.welcome': 'डीपीआरईएस में आपका स्वागत है!',
      'login.selectType': 'कृपया जारी रखने के लिए अपना लॉगिन प्रकार चुनें',
      'login.student': 'छात्र लॉगिन',
      'login.studentDesc': 'सीखने के मॉड्यूल और प्रशिक्षण का उपयोग करें',
      'login.admin': 'एडमिन लॉगिन',
      'login.adminDesc': 'जल्द आ रहा है - संस्थागत प्रबंधन',
      'login.continue': 'जारी रखें',
      'login.back': 'वापस',
      'login.selectInstitution': 'संस्थान प्रकार चुनें',
      'login.institutionQuestion': 'क्या आप स्कूल या कॉलेज में पढ़ रहे हैं?',
      'login.school': 'स्कूल',
      'login.schoolDesc': 'कक्षा 6-12, आयु 10-18',
      'login.college': 'कॉलेज/विश्वविद्यालय',
      'login.collegeDesc': 'स्नातक/स्नातकोत्तर कार्यक्रम',
      'login.enterDetails': 'अपना विवरण दर्ज करें',
      'login.provideInfo': 'कृपया अपना',
      'login.selectSchool': 'अपना स्कूल चुनें',
      'login.selectCollege': 'अपना कॉलेज चुनें',
      'login.chooseSchool': 'अपना स्कूल चुनें',
      'login.chooseCollege': 'अपना कॉलेज चुनें',
      'login.schoolCode': 'स्कूल कोड',
      'login.collegeCode': 'कॉलेज कोड',
      'login.age': 'आयु',
      'login.fullName': 'पूरा नाम',
      'login.enterAge': 'आयु दर्ज करें',
      'login.enterName': 'अपना पूरा नाम दर्ज करें',
      'login.enterHub': 'तैयारी हब में प्रवेश करें',
      'login.buildingSafety': 'शिक्षा के माध्यम से एक सुरक्षित कल का निर्माण',
      'login.poweredBy': 'द्वारा संचालित',
      'login.step1': 'चरण 1: उपयोगकर्ता प्रकार चुनें',
      'login.step2': 'चरण 2: संस्थान प्रकार चुनें',
      'login.step3': 'चरण 3: विवरण दर्ज करें',
      
      // Landing Page
      'landing.hero.title': 'शिक्षा के माध्यम से लचीले समुदायों का निर्माण',
      'landing.hero.subtitle': 'भारत भर के स्कूलों और कॉलेजों के लिए व्यापक आपदा तैयारी प्रशिक्षण',
      'landing.hero.getStarted': 'शुरू करें',
      'landing.hero.learnMore': 'और जानें',
      'landing.quickAccess': 'त्वरित पहुंच',
      'landing.emergency': 'आपातकाल',
      'landing.sos': 'एसओएस अलर्ट',
      'landing.contacts': 'त्वरित संपर्क',
      'landing.report': 'घटना की रिपोर्ट करें',
      'landing.features.title': 'व्यापक आपदा तैयारी प्लेटफॉर्म',
      'landing.features.subtitle': 'शैक्षणिक संस्थानों को रीयल-टाइम अलर्ट, इंटरैक्टिव प्रशिक्षण मॉड्यूल और प्रभावी आपदा प्रतिक्रिया के लिए तल्लीन करने वाले वीआर अनुभवों के साथ सशक्त बनाना।',
      'landing.features.training': 'प्रशिक्षण मॉड्यूल',
      'landing.features.trainingDesc': 'इंटरैक्टिव सामग्री और प्रगति ट्रैकिंग के साथ व्यापक आपदा प्रबंधन प्रशिक्षण।',
      'landing.features.vr': 'वीआर प्रशिक्षण',
      'landing.features.vrDesc': 'भूकंप, आग और अन्य आपातकालीन परिदृश्यों के लिए तल्लीन करने वाले वर्चुअल रियलिटी सिमुलेशन।',
      'landing.features.realtime': 'रीयल-टाइम अलर्ट',
      'landing.features.realtimeDesc': 'आपके संस्थान को तुरंत पहुंचाए गए क्षेत्र-विशिष्ट आपदा अलर्ट और आपातकालीन सूचनाएं।',
      'landing.features.progress': 'एडमिन निरीक्षण',
      'landing.features.progressDesc': 'अधिकारियों और शैक्षणिक प्रशासकों के लिए व्यापक निगरानी और रिपोर्टिंग उपकरण।',
      'landing.stats.title': 'प्रभाव आंकड़े',
      'landing.stats.students': 'प्रशिक्षित छात्र',
      'landing.stats.institutions': 'संस्थान',
      'landing.stats.modules': 'प्रशिक्षण मॉड्यूल',
      'landing.stats.satisfaction': 'संतुष्टि दर',
      'landing.disasters.title': 'हाल की आपदाएं और केस स्टडी',
      'landing.disasters.subtitle': 'वास्तविक आपदाओं से सीखें जिन्होंने शैक्षणिक संस्थानों को प्रभावित किया और कैसे उचित तैयारी ने जीवन बचाए',
      'landing.disasters.cyclone': 'चक्रवात',
      'landing.disasters.flood': 'बाढ़',
      'landing.disasters.earthquake': 'भूकंप',
      'landing.disasters.wildfire': 'जंगलों की आग',
      'landing.disasters.cycloneEmergency': 'चक्रवात आपातकाल',
      'landing.disasters.floodEmergency': 'बाढ़ आपातकाल',
      'landing.disasters.majorEarthquake': 'प्रमुख भूकंप',
      'landing.disasters.tsunamiEmergency': 'सुनामी आपातकाल',
      'landing.disasters.studentsAffected': 'प्रभावित छात्र',
      'landing.disasters.studentsEvacuated': 'सुरक्षित निकाले गए छात्र',
      'landing.disasters.studentsRelocated': 'स्थानांतरित छात्र',
      'landing.disasters.studentsRescued': 'बचाए गए छात्र',
      'landing.disasters.learnMore': 'इस आपदा के बारे में और जानें',
      'landing.disasters.cycloneFani': 'चक्रवात फानी 2019',
      'landing.disasters.cycloneFaniDesc': 'श्रेणी 4 सुपर चक्रवात • ओडिशा, भारत',
      'landing.disasters.cycloneFaniText': 'पूर्व चेतावनी प्रणाली और स्कूल निकासी अभ्यास ने हजारों छात्रों की जान बचाई। 156 स्कूलों का उपयोग राहत केंद्र के रूप में किया गया।',
      'landing.disasters.punjabFloods': 'पंजाब बाढ़ 2023',
      'landing.disasters.punjabFloodsDesc': 'मानसून बाढ़ • पंजाब, भारत',
      'landing.disasters.punjabFloodsText': 'स्कूल अधिकारियों की त्वरित कार्रवाई और समुदायिक तैयारी ने सुनिश्चित किया कि 99% छात्र सुरक्षा तक पहुंचे। 89 स्कूलों ने अस्थायी आश्रयों का काम किया।',
      'landing.disasters.gujarateEarthquake': 'गुजरात भूकंप 2001',
      'landing.disasters.gujarateEarthquakeDesc': '7.7 परिमाण • गुजरात, भारत',
      'landing.disasters.gujarateEarthquakeText': 'इस आपदा ने भारत की पहली व्यापक स्कूल सुरक्षा दिशानिर्देशों का नेतृत्व किया। ड्रॉप, कवर, होल्ड अभ्यास देशभर में अनिवार्य हो गए।',
      'landing.disasters.indianOceanTsunami': 'हिंद महासागर सुनामी 2004',
      'landing.disasters.indianOceanTsunamiDesc': '9.1 भूकंप और सुनामी • तमिलनाडु तट',
      'landing.disasters.indianOceanTsunamiText': 'भारत की तटीय पूर्व चेतावनी प्रणालियों का नेतृत्व किया। चेन्नई के स्कूलों में अब सुनामी निकासी प्रोटोकॉल और नियमित अभ्यास हैं।',
      'landing.disasters.buildPreparedness': 'क्या आप अपने स्कूल की आपदा तैयारी बनाने के लिए तैयार हैं?',
      'landing.disasters.joinInstitutions': 'हजारों संस्थानों से जुड़ें जिन्होंने डीपीआरईएस प्रशिक्षण के माध्यम से अपनी आपातकालीन प्रतिक्रिया में सुधार किया है',
      'landing.disasters.startTraining': 'आपातकालीन प्रशिक्षण अभी शुरू करें',
      
      // Dashboard
      'dashboard.welcome': 'अपने डैशबोर्ड में आपका स्वागत है',
      'dashboard.overview': 'अवलोकन',
      'dashboard.alerts.title': 'आपातकालीन अलर्ट',
      'dashboard.alerts.noAlerts': 'आपके क्षेत्र में कोई सक्रिय अलर्ट नहीं',
      'dashboard.alerts.checkback': 'हम आपको किसी भी आपातकालीन स्थिति की सूचना देंगे',
      'dashboard.progress.title': 'प्रशिक्षण प्रगति',
      'dashboard.progress.overall': 'समग्र प्रगति',
      'dashboard.progress.modules': 'पूरे किए गए मॉड्यूल',
      'dashboard.progress.certificates': 'अर्जित प्रमाणपत्र',
      'dashboard.progress.hours': 'प्रशिक्षण घंटे',
      'dashboard.quickActions': 'त्वरित क्रियाएं',
      'dashboard.startTraining': 'प्रशिक्षण शुरू करें',
      'dashboard.viewCertificates': 'प्रमाणपत्र देखें',
      'dashboard.emergencyKit': 'आपातकालीन किट',
      'dashboard.practiceQuiz': 'अभ्यास प्रश्नोत्तरी',
      'dashboard.recentActivity': 'हाल की गतिविधि',
      'dashboard.completedModule': 'पूरा किया',
      'dashboard.earnedCertificate': 'में प्रमाणपत्र अर्जित किया',
      'dashboard.startedModule': 'शुरू किया',
      'dashboard.viewAll': 'सभी देखें',
      'dashboard.alerts.description': 'क्षेत्र-विशिष्ट आपदा अलर्ट और सूचनाएं',
      'dashboard.sos.success': 'निकटतम आपदा प्राधिकरण को एसओएस अलर्ट भेजा गया।',
      'dashboard.sos.confirm': 'आपातकालीन एसओएस',
      'dashboard.sos.description': 'क्या आप वाकई एसओएस ट्रिगर करना चाहते हैं? यह निकटतम आपदा प्रबंधन अधिकारियों को अलर्ट करेगा।',
      'dashboard.sos.confirmButton': 'एसओएस पुष्टि करें',
      'dashboard.incident.success': 'घटना रिपोर्ट सफलतापूर्वक भेजी गई।',
      'dashboard.learningProgress': 'शिक्षा प्रगति',
      'dashboard.progressDesc': 'आपकी आपदा तैयारी प्रशिक्षण प्रगति',
      'dashboard.modulesCompleted': 'पूर्ण मॉड्यूल',
      'dashboard.vrTrainingsCompleted': 'पूर्ण वीआर प्रशिक्षण',
      'dashboard.latestQuizScore': 'नवीनतम क्विज़ स्कोर',
      'dashboard.recentActivityDesc': 'आपके नवीनतम शिक्षण अपडेट',
      'dashboard.keepProgress': 'बढ़िया काम! प्रगति जारी रखें',
      'dashboard.hoursAgo': 'घंटे पहले',
      'dashboard.heavyRainfall': 'भारी बारिश',
      'dashboard.earthquakeTremors': 'भूकंप के झटके',
      'dashboard.alert': 'अलर्ट',
      'dashboard.regionSpecific': 'क्षेत्र-विशिष्ट आपदा अलर्ट और सूचनाएं',
      'dashboard.moderateRainfall': 'आपके क्षेत्र में मध्यम से भारी बारिश की उम्मीद है। बाढ़ तैयारी प्रोटोकॉल की समीक्षा करें।',
      'dashboard.minorSeismic': 'मामूली भूकंपीय गतिविधि का पता चला है। सतर्क रहें और भूकंप सुरक्षा प्रक्रियाओं की समीक्षा करें।',
      'dashboard.emergencyResponse': 'आपातकालीन प्रतिक्रिया',
      'dashboard.moduleCompleted': 'मॉड्यूल 4 पूरा – आपातकालीन प्रतिक्रिया',
      'dashboard.chennaiDistrict': 'चेन्नई जिला',
      'dashboard.tamilNaduRegion': 'तमिलनाडु क्षेत्र',
      'dashboard.alerts.heavyRainfall': 'भारी बारिश अलर्ट',
      'dashboard.alerts.earthquakeTremors': 'भूकंप के झटके अलर्ट',
      'dashboard.alerts.rainfallDesc': 'आपके क्षेत्र में मध्यम से भारी बारिश की उम्मीद है। बाढ़ तैयारी प्रोटोकॉल की समीक्षा करें।',
      'dashboard.alerts.seismicDesc': 'मामूली भूकंपीय गतिविधि का पता चला है। सतर्क रहें और भूकंप सुरक्षा प्रक्रियाओं की समीक्षा करें।',
      'dashboard.alerts.timeAgo2h': '2 घंटे पहले',
      'dashboard.alerts.timeAgo6h': '6 घंटे पहले',
      'dashboard.alerts.chennaiDistrict': 'चेन्नई जिला',
      'dashboard.quickAccess.title': 'त्वरित पहुंच',
      'dashboard.quickAccess.description': 'अक्सर उपयोग किए जाने वाले उपकरण और संसाधन',
      'dashboard.quickAccess.safetyProtocols': 'सुरक्षा प्रोटोकॉल',
      'dashboard.quickAccess.evacuationRoutes': 'निकासी मार्ग',
      'dashboard.quickAccess.emergencyDirectory': 'आपातकालीन निर्देशिका',
      'dashboard.quickAccess.incidentReports': 'घटना रिपोर्ट',
      'dashboard.emergencyContacts': 'आपातकालीन संपर्क',
      'dashboard.emergencyContacts.fire': 'दमकल विभाग',
      'dashboard.emergencyContacts.police': 'पुलिस',
      'dashboard.emergencyContacts.medical': 'चिकित्सा आपातकाल',
      'dashboard.emergencyContacts.disaster': 'आपदा प्रबंधन',
      'dashboard.emergencyContacts.tapToCall': 'आपातकालीन सेवाओं तक त्वरित पहुंच। तुरंत कॉल करने के लिए टैप करें।',
  'dashboard.emergencyContacts.call': 'कॉल करें',
      'dashboard.recentActivity.module4': 'मॉड्यूल 4 पूरा – आपातकालीन प्रतिक्रिया',
      'dashboard.recentActivity.vrFire': 'वीआर अग्नि ड्रिल पूरा',
      'dashboard.recentActivity.evacuationTime': 'निकासी का समय: 3 मिनट 45 सेकंड',
      'dashboard.recentActivity.quizEarthquake': 'भूकंप सुरक्षा पर क्विज़ में 85% स्कोर',
      'dashboard.recentActivity.performance': 'औसत से अधिक प्रदर्शन!',
      'dashboard.recentActivity.keepProgress': 'बढ़िया काम! प्रगति जारी रखें',
      'dashboard.recentActivity.timeAgo1h': '1 घंटे पहले',
      'dashboard.recentActivity.timeAgo2d': '2 दिन पहले',
      'dashboard.recentActivity.timeAgo3d': '3 दिन पहले',
      'dashboard.incident.title': 'घटना की रिपोर्ट करें',
      'dashboard.incident.description': 'आप जिस घटना की रिपोर्ट करना चाहते हैं उसका विवरण प्रदान करें।',
      'dashboard.incident.type': 'घटना का प्रकार',
      'dashboard.incident.selectType': 'घटना का प्रकार चुनें',
      'dashboard.incident.fire': '🔥 आग',
      'dashboard.incident.earthquake': '🌍 भूकंप',
      'dashboard.incident.medical': '🚑 चिकित्सा आपातकाल',
      'dashboard.incident.other': '⚠️ अन्य',
      'dashboard.incident.location': 'स्थान',
      'dashboard.incident.locationPlaceholder': 'स्थान का विवरण दर्ज करें',
      'dashboard.incident.descriptionLabel': 'संक्षिप्त विवरण',
      'dashboard.incident.descriptionPlaceholder': 'घटना का संक्षेप में वर्णन करें',
      'dashboard.incident.submit': 'रिपोर्ट जमा करें',
      
      // Modules Page
      'modules.title': 'प्रशिक्षण मॉड्यूल',
      'modules.subtitle': 'प्रगतिशील सीखने के चरणों के माध्यम से आपदा तैयारी में महारत हासिल करें',
      'modules.journey': 'आपकी तैयारी यात्रा',
      'modules.yourProgress': 'आपकी प्रगति',
      'modules.schoolAverage': 'आपके स्कूल का औसत',
      'modules.collegeAverage': 'आपके कॉलेज का औसत',
      'modules.friendComparison': 'दोस्त तुलना',
      'modules.overall': 'समग्र',
      'modules.modules': 'मॉड्यूल',
      'modules.vrTrainings': 'वीआर प्रशिक्षण',
      'modules.quizAverage': 'प्रश्नोत्तरी औसत',
      'modules.school': 'स्कूल',
      'modules.college': 'कॉलेज',
      'modules.selectFriend': 'तुलना के लिए एक दोस्त चुनें',
      'modules.progress': 'प्रगति',
      'modules.duration': 'अवधि',
      'modules.students': 'छात्र',
      'modules.keyTopics': 'मुख्य विषय',
      'modules.reviewModule': 'मॉड्यूल की समीक्षा करें',
      'modules.continueLearning': 'सीखना जारी रखें',
      'modules.completePrevious': 'पिछले मॉड्यूल पूरे करें',
      'modules.additionalResources': 'अतिरिक्त संसाधन',
      'modules.resourcesDesc': 'पूरक सामग्री और संदर्भ',
      'modules.resourceLibrary': 'संसाधन पुस्तकालय',
      'modules.bestPractices': 'सर्वोत्तम अभ्यास',
      'modules.caseStudies': 'केस स्टडी',
      'modules.completed': 'पूर्ण',
      'modules.inProgress': 'प्रगति में',
      'modules.locked': 'लॉक',
      'modules.aheadOfAverage': 'अद्भुत! आप अपने स्कूल के औसत से आगे हैं! 🚀',
      'modules.catchingUp': 'बहुत करीब! आप तेजी से पकड़ रहे हैं! 💪',
      'modules.keepGoing': 'चलते रहें! हर कदम मायने रखता है! 🌟',
      'modules.yourSchool': 'आपका स्कूल',
      'modules.yourCollege': 'आपका कॉलेज',
      'modules.aheadOfFriend': 'आप {percent}% आगे हैं! 🎉',
      'modules.behindFriend': 'आप {percent}% पीछे हैं। चलते रहें! 💪',
      'modules.minutesShort': 'मिनट',
      'modules.video': 'वीडियो',
      'modules.interactive': 'इंटरैक्टिव',
      'modules.mixed': 'मिश्रित',
      'modules.simulation': 'सिमुलेशन',
      
      // VR Training Page
      'vr.title': 'वर्चुअल रियलिटी प्रशिक्षण',
      'vr.subtitle': 'मोबाइल वीआर का उपयोग करके तल्लीन करने वाला आपदा तैयारी सिमुलेशन',
      'vr.gettingStarted': 'मोबाइल वीआर प्रशिक्षण के साथ शुरुआत',
      'vr.setupDesc': 'तल्लीन करने वाले प्रशिक्षण के लिए अपने स्मार्टफोन और कार्डबोर्ड वीआर व्यूअर का उपयोग करें',
      'vr.smartphone': 'स्मार्टफोन',
      'vr.smartphoneDesc': 'जाइरोस्कोप सेंसर के साथ Android 6.0+ या iOS 10+',
      'vr.cardboardViewer': 'कार्डबोर्ड वीआर व्यूअर',
      'vr.cardboardDesc': 'DIY कार्डबोर्ड या Google Cardboard संगत व्यूअर',
      'vr.headphones': 'हेडफोन',
      'vr.headphonesDesc': 'बेहतर तल्लीनता के लिए वैकल्पिक ईयरफोन',
      'vr.downloadApp': 'वीआर ऐप डाउनलोड करें',
      'vr.setupGuide': 'सेटअप गाइड',
      'vr.qrCodeDesc': 'DPRES VR ऐप डाउनलोड करने के लिए अपने फोन से इस QR कोड को स्कैन करें',
      'vr.comingSoon': 'जल्द आ रहा है',
      'vr.available': 'उपलब्ध',
      'vr.beginner': 'शुरुआती',
      'vr.intermediate': 'मध्यम',
      'vr.advanced': 'उन्नत',
      'vr.startTraining': 'वीआर प्रशिक्षण शुरू करें',
      'vr.totalSessions': 'कुल वीआर सत्र',
      'vr.completionRate': 'पूर्णता दर',
      'vr.avgSessionTime': 'औसत सत्र समय',
      'vr.avgTime': '18 मिनट',
      'vr.userRating': 'उपयोगकर्ता रेटिंग',
      'vr.trainingPreview': 'वीआर प्रशिक्षण पूर्वावलोकन',
      'vr.previewDesc': 'हमारे तल्लीन करने वाले प्रशिक्षण वातावरण का एक नमूना अनुभव करें',
      'vr.previewEnvironment': 'वीआर वातावरण पूर्वावलोकन',
      'vr.trainingEnvironmentAlt': 'वीआर प्रशिक्षण वातावरण',
      'vr.earthquakeResponse': 'भूकंप प्रतिक्रिया',
      'vr.earthquakeDesc': 'वास्तविक भूकंप परिदृश्यों का अनुभव करें और सुरक्षित वर्चुअल वातावरण में उचित ड्रॉप, कवर और होल्ड तकनीकें सीखें।',
      'vr.fireEmergency': 'अग्नि आपातकाल',
      'vr.fireDesc': 'अग्नि आपातकालीन परिदृश्यों से गुजरें, निकासी मार्गों का अभ्यास करें, और अग्नि सुरक्षा उपकरणों का उचित उपयोग सीखें।',
      'vr.floodResponse': 'बाढ़ प्रतिक्रिया',
      'vr.floodDesc': 'विभिन्न बाढ़ परिदृश्यों और वातावरणों में बाढ़ सुरक्षा प्रोटोकॉल और निकासी प्रक्रियाओं को सीखें।',
      'vr.cyclonePreparedness': 'चक्रवात तैयारी',
      'vr.cycloneDesc': 'गंभीर मौसम स्थितियों का अनुभव करें और चक्रवाती तूफानों के दौरान उचित आश्रय और सुरक्षा उपायों को सीखें।',
      'vr.duration15to20': '15-20 मिनट',
      'vr.duration12to18': '12-18 मिनट',
      'vr.duration20to25': '20-25 मिनट',
      'vr.duration18to22': '18-22 मिनट',
      
      // Common
      'common.loading': 'लोड हो रहा है...',
      'common.error': 'त्रुटि',
      'common.success': 'सफलता',
      'common.cancel': 'रद्द करें',
      'common.save': 'सहेजें',
      'common.edit': 'संपादित करें',
      'common.delete': 'हटाएं',
      'common.view': 'देखें',
      'common.close': 'बंद करें',
    },
    bn: {
      // Navigation
      'nav.dashboard': 'ড্যাশবোর্ড',
      'nav.modules': 'প্রশিক্ষণ মডিউল',
      'nav.vr': 'ভিআর প্রশিক্ষণ',
      'nav.admin': 'অ্যাডমিন',
      'nav.logout': 'লগআউট',
      'nav.menu': 'মেনু',
      'nav.darkMode': 'ডার্ক মোড',
      
      // Login Page
      'login.title': 'ডিপিআরইএস লগইন',
      'login.subtitle': 'দুর্যোগ প্রস্তুতি এবং প্রতিক্রিয়া শিক্ষা ব্যবস্থা',
      'login.madeInIndia': 'মেড ইন ইন্ডিয়া',
      'login.welcome': 'ডিপিআরইএসে স্বাগতম!',
      'login.selectType': 'অব্যাহত রাখতে দয়া করে আপনার লগইন ধরন নির্বাচন করুন',
      'login.student': 'ছাত্র লগইন',
      'login.studentDesc': 'শেখার মডিউল এবং প্রশিক্ষণ অ্যাক্সেস করুন',
      'login.admin': 'অ্যাডমিন লগইন',
      'login.adminDesc': 'শীঘ্রই আসছে - প্রাতিষ্ঠানিক ব্যবস্থাপনা',
      'login.continue': 'অব্যাহত রাখুন',
      'login.back': 'ফিরে যান',
      'login.selectInstitution': 'প্রতিষ্ঠানের ধরন নির্বাচন করুন',
      'login.institutionQuestion': 'আপনি কি স্কুল নাকি কলেজে পড়ছেন?',
      'login.school': 'স্কুল',
      'login.schoolDesc': 'ক্লাস ৬-১২, বয়স ১০-১৮',
      'login.college': 'কলেজ/বিশ্ববিদ্যালয়',
      'login.collegeDesc': 'স্নাতক/স্নাতকোত্তর প্রোগ্রাম',
      'login.enterDetails': 'আপনার বিবরণ প্রবেশ করুন',
      'login.provideInfo': 'দয়া করে আপনার',
      'login.selectSchool': 'আপনার স্কুল নির্বাচন করুন',
      'login.selectCollege': 'আপনার কলেজ নির্বাচন করুন',
      'login.chooseSchool': 'আপনার স্কুল বেছে নিন',
      'login.chooseCollege': 'আপনার কলেজ বেছে নিন',
      'login.schoolCode': 'স্কুল কোড',
      'login.collegeCode': 'কলেজ কোড',
      'login.age': 'বয়স',
      'login.fullName': 'পুরো নাম',
      'login.enterAge': 'বয়স প্রবেশ করুন',
      'login.enterName': 'আপনার পুরো নাম প্রবেশ করুন',
      'login.enterHub': 'প্রস্তুতি হাবে প্রবেশ করুন',
      'login.buildingSafety': 'শিক্ষার মাধ্যমে একটি নিরাপদ আগামীকাল গড়ে তোলা',
      'login.poweredBy': 'দ্বারা চালিত',
      'login.step1': 'ধাপ ১: ব্যবহারকারীর ধরন নির্বাচন করুন',
      'login.step2': 'ধাপ ২: প্রতিষ্ঠানের ধরন নির্বাচন করুন',
      'login.step3': 'ধাপ ৩: বিবরণ প্রবেশ করুন',
      
      // Landing Page
      'landing.hero.title': 'শিক্ষার মাধ্যমে স্থিতিস্থাপক সম্প্রদায় গড়ে তোলা',
      'landing.hero.subtitle': 'ভারত জুড়ে স্কুল এবং কলেজের জন্য ব্যাপক দুর্যোগ প্রস্তুতি প্রশিক্ষণ',
      'landing.hero.getStarted': 'শুরু করুন',
      'landing.hero.learnMore': 'আরো জানুন',
      'landing.quickAccess': 'দ্রুত অ্যাক্সেস',
      'landing.emergency': 'জরুরি অবস্থা',
      'landing.sos': 'এসওএস সতর্কতা',
      'landing.contacts': 'দ্রুত যোগাযোগ',
      'landing.report': 'ঘটনা রিপোর্ট করুন',
      'landing.features.title': 'ব্যাপক দুর্যোগ প্রস্তুতি প্ল্যাটফর্ম',
      'landing.features.subtitle': 'শিক্ষা প্রতিষ্ঠানগুলিকে রিয়েল-টাইম সতর্কতা, ইন্টারঅ্যাক্টিভ প্রশিক্ষণ মডিউল এবং কার্যকর দুর্যোগ প্রতিক্রিয়ার জন্য নিমজ্জনকারী ভিআর অভিজ্ঞতা দিয়ে ক্ষমতায়ন করা।',
      'landing.features.training': 'প্রশিক্ষণ মডিউল',
      'landing.features.trainingDesc': 'ইন্টারঅ্যাক্টিভ বিষয়বস্তু এবং অগ্রগতি ট্র্যাকিং সহ ব্যাপক দুর্যোগ ব্যবস্থাপনা প্রশিক্ষণ।',
      'landing.features.vr': 'ভিআর প্রশিক্ষণ',
      'landing.features.vrDesc': 'ভূমিকম্প, আগুন এবং অন্যান্য জরুরি পরিস্থিতির জন্য নিমজ্জনকারী ভার্চুয়াল রিয়েলিটি সিমুলেশন।',
      'landing.features.realtime': 'রিয়েল-টাইম সতর্কতা',
      'landing.features.realtimeDesc': 'আপনার প্রতিষ্ঠানে তাৎক্ষণিকভাবে পৌঁছানো অঞ্চল-নির্দিষ্ট দুর্যোগ সতর্কতা এবং জরুরি বিজ্ঞপ্তি।',
      'landing.features.progress': 'প্রশাসনিক তদারকি',
      'landing.features.progressDesc': 'কর্তৃপক্ষ এবং শিক্ষা প্রশাসকদের জন্য ব্যাপক মনিটরিং এবং রিপোর্টিং সরঞ্জাম।',
      'landing.stats.title': 'প্রভাব পরিসংখ্যান',
      'landing.stats.students': 'প্রশিক্ষিত ছাত্র',
      'landing.stats.institutions': 'প্রতিষ্ঠান',
      'landing.stats.modules': 'প্রশিক্ষণ মডিউল',
      'landing.stats.satisfaction': 'সন্তুষ্টির হার',
      'landing.disasters.title': 'সাম্প্রতিক দুর্যোগ এবং কেস স্টাডি',
      'landing.disasters.subtitle': 'বাস্তব দুর্যোগ থেকে শিখুন যা শিক্ষা প্রতিষ্ঠানগুলিকে প্রভাবিত করেছে এবং কীভাবে যথাযথ প্রস্তুতি জীবন রক্ষা করেছে',
      'landing.disasters.cyclone': 'ঘূর্ণিঝড়',
      'landing.disasters.flood': 'বন্যা',
      'landing.disasters.earthquake': 'ভূমিকম্প',
      'landing.disasters.wildfire': 'দাবানল',
      'landing.disasters.cycloneEmergency': 'ঘূর্ণিঝড় জরুরি অবস্থা',
      'landing.disasters.floodEmergency': 'বন্যা জরুরি অবস্থা',
      'landing.disasters.majorEarthquake': 'প্রধান ভূমিকম্প',
      'landing.disasters.tsunamiEmergency': 'সুনামি জরুরি অবস্থা',
      'landing.disasters.studentsAffected': 'প্রভাবিত ছাত্র',
      'landing.disasters.studentsEvacuated': 'নিরাপদে সরিয়ে নেওয়া ছাত্র',
      'landing.disasters.studentsRelocated': 'স্থানান্তরিত ছাত্র',
      'landing.disasters.studentsRescued': 'উদ্ধারকৃত ছাত্র',
      'landing.disasters.learnMore': 'এই দুর্যোগ সম্পর্কে আরও জানুন',
      'landing.disasters.cycloneFani': 'ঘূর্ণিঝড় ফানি ২০১৯',
      'landing.disasters.cycloneFaniDesc': 'শ্রেণী ৪ সুপার সাইক্লোন • ওড়িশা, ভারত',
      'landing.disasters.cycloneFaniText': 'পূর্ব সতর্কীকরণ ব্যবস্থা এবং স্কুল নিকাশী অনুশীলন হাজার হাজার ছাত্রের প্রাণ বাঁচিয়েছে। ১৫৬টি স্কুল ত্রাণ কেন্দ্র হিসেবে ব্যবহৃত হয়েছে।',
      'landing.disasters.punjabFloods': 'পাঞ্জাব বন্যা ২০২৩',
      'landing.disasters.punjabFloodsDesc': 'মৌসুমি বন্যা • পাঞ্জাব, ভারত',
      'landing.disasters.punjabFloodsText': 'স্কুল কর্তৃপক্ষের দ্রুত পদক্ষেপ এবং সমুদায়িক প্রস্তুতি নিশ্চিত করেছে যে ৯৯% ছাত্র নিরাপত্তায় পৌঁছেছে। ৮৯টি স্কুল অস্থায়ী আশ্রয়স্থল হিসেবে কাজ করেছে।',
      'landing.disasters.gujarateEarthquake': 'গুজরাত ভূমিকম্প ২০০১',
      'landing.disasters.gujarateEarthquakeDesc': '৭.৭ মাত্রা • গুজরাত, ভারত',
      'landing.disasters.gujarateEarthquakeText': 'এই দুর্যোগ ভারতের প্রথম ব্যাপক স্কুল নিরাপত্তা নির্দেশিকার নেতৃত্ব দিয়েছে। ড্রপ, কভার, হোল্ড অনুশীলন দেশব্যাপী বাধ্যতামূলক হয়ে উঠেছে।',
      'landing.disasters.indianOceanTsunami': 'ভারত মহাসাগর সুনামি ২০০৪',
      'landing.disasters.indianOceanTsunamiDesc': '৯.১ ভূমিকম্প ও সুনামি • তামিলনাড়ু উপকূল',
      'landing.disasters.indianOceanTsunamiText': 'ভারতের উপকূলীয় পূর্ব সতর্কীকরণ ব্যবস্থার নেতৃত্ব দিয়েছে। চেন্নাইয়ের স্কুলগুলিতে এখন সুনামি নিকাশী প্রোটোকল এবং নিয়মিত অনুশীলন রয়েছে।',
      'landing.disasters.buildPreparedness': 'আপনার স্কুলের দুর্যোগ প্রস্তুতি তৈরি করতে প্রস্তুত?',
      'landing.disasters.joinInstitutions': 'হাজার হাজার প্রতিষ্ঠানের সাথে যোগ দিন যারা ডিপিআরইএস প্রশিক্ষণের মাধ্যমে তাদের জরুরি প্রতিক্রিয়া উন্নত করেছে',
      'landing.disasters.startTraining': 'এখনই জরুরি প্রশিক্ষণ শুরু করুন',
      
      // Dashboard
      'dashboard.welcome': 'আপনার ড্যাশবোর্ডে স্বাগতম',
      'dashboard.overview': 'সারসংক্ষেপ',
      'dashboard.alerts.title': 'জরুরি সতর্কতা',
      'dashboard.alerts.noAlerts': 'আপনার এলাকায় কোনো সক্রিয় সতর্কতা নেই',
      'dashboard.alerts.checkback': 'আমরা আপনাকে যেকোনো জরুরি পরিস্থিতির জানাবো',
      'dashboard.progress.title': 'প্রশিক্ষণের অগ্রগতি',
      'dashboard.progress.overall': 'সামগ্রিক অগ্রগতি',
      'dashboard.progress.modules': 'সম্পন্ন মডিউল',
      'dashboard.progress.certificates': 'অর্জিত সার্টিফিকেট',
      'dashboard.progress.hours': 'প্রশিক্ষণের ঘন্টা',
      'dashboard.quickActions': 'দ্রুত ক্রিয়া',
      'dashboard.startTraining': 'প্রশিক্ষণ শুরু করুন',
      'dashboard.viewCertificates': 'সার্টিফিকেট দেখুন',
      'dashboard.emergencyKit': 'জরুরি কিট',
      'dashboard.practiceQuiz': 'অনুশীলন কুইজ',
      'dashboard.recentActivity': 'সাম্প্রতিক কার্যকলাপ',
      'dashboard.completedModule': 'সম্পন্ন',
      'dashboard.earnedCertificate': 'এ সার্টিফিকেট অর্জন করেছেন',
      'dashboard.startedModule': 'শুরু করেছেন',
      'dashboard.viewAll': 'সবগুলো দেখুন',
      'dashboard.alerts.description': 'অঞ্চল-নির্দিষ্ট দুর্যোগ সতর্কতা এবং বিজ্ঞপ্তি',
      'dashboard.sos.success': 'নিকটতম দুর্যোগ কর্তৃপক্ষে এসওএস সতর্কতা পাঠানো হয়েছে।',
      'dashboard.sos.confirm': 'জরুরি এসওএস',
      'dashboard.sos.description': 'আপনি কি সত্যিই এসওএস ট্রিগার করতে চান? এটি নিকটতম দুর্যোগ ব্যবস্থাপনা কর্তৃপক্ষকে সতর্ক করবে।',
      'dashboard.sos.confirmButton': 'এসওএস নিশ্চিত করুন',
      'dashboard.incident.success': 'ঘটনা রিপোর্ট সফলভাবে পাঠানো হয়েছে।',
      'dashboard.learningProgress': 'শেখার অগ্রগতি',
      'dashboard.progressDesc': 'আপনার দুর্যোগ প্রস্তুতি প্রশিক্ষণের অগ্রগতি',
      'dashboard.modulesCompleted': 'সম্পন্ন মডিউল',
      'dashboard.vrTrainingsCompleted': 'সম্পন্ন ভিআর প্রশিক্ষণ',
      'dashboard.latestQuizScore': 'সর্বশেষ কুইজ স্কোর',
      'dashboard.recentActivityDesc': 'আপনার সর্বশেষ শেখার আপডেট',
      'dashboard.keepProgress': 'চমৎকার কাজ! অগ্রগতি বজায় রাখুন',
      'dashboard.hoursAgo': 'ঘন্টা আগে',
      'dashboard.heavyRainfall': 'প্রবল বৃষ্টিপাত',
      'dashboard.earthquakeTremors': 'ভূমিকম্পের ঝাঁকুনি',
      'dashboard.alert': 'সতর্কতা',
      'dashboard.regionSpecific': 'অঞ্চল-নির্দিষ্ট দুর্যোগ সতর্কতা এবং বিজ্ঞপ্তি',
      'dashboard.moderateRainfall': 'আপনার অঞ্চলে মাঝারি থেকে প্রবল বৃষ্টিপাতের আশা করা হচ্ছে। বন্যা প্রস্তুতি প্রোটোকল পর্যালোচনা করুন।',
      'dashboard.minorSeismic': 'সামান্য ভূমিকম্পীয় কার্যকলাপ শনাক্ত হয়েছে। সতর্ক থাকুন এবং ভূমিকম্প নিরাপত্তা পদ্ধতি পর্যালোচনা করুন।',
      'dashboard.emergencyResponse': 'জরুরি প্রতিক্রিয়া',
      'dashboard.moduleCompleted': 'মডিউল ৪ সম্পন্ন – জরুরি প্রতিক্রিয়া',
      'dashboard.chennaiDistrict': 'চেন্নাই জেলা',
      'dashboard.tamilNaduRegion': 'তামিলনাড়ু অঞ্চল',
      'dashboard.alerts.heavyRainfall': 'প্রবল বৃষ্টিপাত সতর্কতা',
      'dashboard.alerts.earthquakeTremors': 'ভূমিকম্পের ঝাঁকুনি সতর্কতা',
      'dashboard.alerts.rainfallDesc': 'আপনার অঞ্চলে মাঝারি থেকে প্রবল বৃষ্টিপাতের আশা করা হচ্ছে। বন্যা প্রস্তুতি প্রোটোকল পর্যালোচনা করুন।',
      'dashboard.alerts.seismicDesc': 'সামান্য ভূমিকম্পীয় কার্যকলাপ শনাক্ত হয়েছে। সতর্ক থাকুন এবং ভূমিকম্প নিরাপত্তা পদ্ধতি পর্যালোচনা করুন।',
      'dashboard.alerts.timeAgo2h': '২ ঘন্টা আগে',
      'dashboard.alerts.timeAgo6h': '৬ ঘন্টা আগে',
      'dashboard.alerts.chennaiDistrict': 'চেন্নাই জেলা',
      'dashboard.quickAccess.title': 'দ্রুত অ্যাক্সেস',
      'dashboard.quickAccess.description': 'প্রায়শই ব্যবহৃত সরঞ্জাম এবং সম্পদ',
      'dashboard.quickAccess.safetyProtocols': 'নিরাপত্তা প্রোটোকল',
      'dashboard.quickAccess.evacuationRoutes': 'নিকাশী রুট',
      'dashboard.quickAccess.emergencyDirectory': 'জরুরি ডিরেক্টরি',
      'dashboard.quickAccess.incidentReports': 'ঘটনা রিপোর্ট',
      'dashboard.emergencyContacts': 'জরুরি যোগাযোগ',
      'dashboard.emergencyContacts.fire': 'দমকল বিভাগ',
      'dashboard.emergencyContacts.police': 'পুলিশ',
      'dashboard.emergencyContacts.medical': 'চিকিৎসা জরুরি অবস্থা',
      'dashboard.emergencyContacts.disaster': 'দুর্যোগ ব্যবস্থাপনা',
      'dashboard.emergencyContacts.tapToCall': 'জরুরি সেবায় দ্রুত অ্যাক্সেস। তাৎক্ষণিক কল করতে ট্যাপ করুন।',
  'dashboard.emergencyContacts.call': 'কল করুন',
      'dashboard.recentActivity.module4': 'মডিউল ৪ সম্পন্ন – জরুরি প্রতিক্রিয়া',
      'dashboard.recentActivity.vrFire': 'ভিআর অগ্নি ড্রিল সম্পন্ন',
      'dashboard.recentActivity.evacuationTime': 'নিকাশীর সময়: ৩ মিনিট ৪৫ সেকেন্ড',
      'dashboard.recentActivity.quizEarthquake': 'ভূমিকম্প নিরাপত্তায় কুইজে ৮৫% স্কোর',
      'dashboard.recentActivity.performance': 'গড়ের চেয়ে ভাল পারফরম্যান্স!',
      'dashboard.recentActivity.keepProgress': 'দুর্দান্ত কাজ! অগ্রগতি বজায় রাখুন',
      'dashboard.recentActivity.timeAgo1h': '১ ঘন্টা আগে',
      'dashboard.recentActivity.timeAgo2d': '২ দিন আগে',
      'dashboard.recentActivity.timeAgo3d': '৩ দিন আগে',
      'dashboard.incident.title': 'ঘটনা রিপোর্ট করুন',
      'dashboard.incident.description': 'আপনি যে ঘটনাটি রিপোর্ট করতে চান তার বিবরণ প্রদান করুন।',
      'dashboard.incident.type': 'ঘটনার ধরন',
      'dashboard.incident.selectType': 'ঘটনার ধরন নির্বাচন করুন',
      'dashboard.incident.fire': '🔥 আগুন',
      'dashboard.incident.earthquake': '🌍 ভূমিকম্প',
      'dashboard.incident.medical': '🚑 চিকিৎসা জরুরি অবস্থা',
      'dashboard.incident.other': '⚠️ অন্যান্য',
      'dashboard.incident.location': 'অবস্থান',
      'dashboard.incident.locationPlaceholder': 'অবস্থানের বিবরণ প্রবেশ করুন',
      'dashboard.incident.descriptionLabel': 'সংক্ষিপ্ত বিবরণ',
      'dashboard.incident.descriptionPlaceholder': 'ঘটনাটি সংক্ষেপে বর্ণনা করুন',
      'dashboard.incident.submit': 'রিপোর্ট জমা দিন',
      
      // Modules Page
      'modules.title': 'প্রশিক্ষণ মডিউল',
      'modules.subtitle': 'প্রগতিশীল শেখার পর্যায়ের মাধ্যমে দুর্যোগ প্রস্তুতিতে দক্ষতা অর্জন করুন',
      'modules.journey': 'আপনার প্রস্তুতির যাত্রা',
      'modules.yourProgress': 'আপনার অগ্রগতি',
      'modules.schoolAverage': 'আপনার স্কুলের গড়',
      'modules.collegeAverage': 'আপনার কলেজের গড়',
      'modules.friendComparison': 'বন্ধুর তুলনা',
      'modules.overall': 'সামগ্রিক',
      'modules.modules': 'মডিউল',
      'modules.vrTrainings': 'ভিআর প্রশিক্ষণ',
      'modules.quizAverage': 'কুইজের গড়',
      'modules.school': 'স্কুল',
      'modules.college': 'কলেজ',
      'modules.selectFriend': 'তুলনার জন্য একজন বন্ধু নির্বাচন করুন',
      'modules.progress': 'অগ্রগতি',
      'modules.duration': 'সময়কাল',
      'modules.students': 'ছাত্র',
      'modules.keyTopics': 'মূল বিষয়',
      'modules.reviewModule': 'মডিউল পর্যালোচনা করুন',
      'modules.continueLearning': 'শেখা অব্যাহত রাখুন',
      'modules.completePrevious': 'পূর্ববর্তী মডিউল সম্পন্ন করুন',
      'modules.additionalResources': 'অতিরিক্ত সম্পদ',
      'modules.resourcesDesc': 'সম্পূরক উপকরণ এবং তথ্যসূত্র',
      'modules.resourceLibrary': 'সম্পদ গ্রন্থাগার',
      'modules.bestPractices': 'সর্বোত্তম অনুশীলন',
      'modules.caseStudies': 'কেস স্টাডি',
      'modules.completed': 'সম্পন্ন',
      'modules.inProgress': 'চলমান',
      'modules.locked': 'লক',
      'modules.aheadOfAverage': 'অসাধারণ! আপনি আপনার স্কুলের গড়ের চেয়ে এগিয়ে! 🚀',
      'modules.catchingUp': 'প্রায় পৌঁছে গেছেন! আপনি দ্রুত এগিয়ে যাচ্ছেন! 💪',
      'modules.keepGoing': 'চালিয়ে যান! প্রতিটি পদক্ষেপ গুরুত্বপূর্ণ! 🌟',
      'modules.yourSchool': 'আপনার স্কুল',
      'modules.yourCollege': 'আপনার কলেজ',
      'modules.aheadOfFriend': 'আপনি {percent}% এগিয়ে! 🎉',
      'modules.behindFriend': 'আপনি {percent}% পিছিয়ে। চালিয়ে যান! 💪',
      'modules.minutesShort': 'মিনিট',
      'modules.video': 'ভিডিও',
      'modules.interactive': 'ইন্টারঅ্যাক্টিভ',
      'modules.mixed': 'মিশ্র',
      'modules.simulation': 'সিমুলেশন',
      
      // VR Training Page
      'vr.title': 'ভার্চুয়াল রিয়েলিটি প্রশিক্ষণ',
      'vr.subtitle': 'মোবাইল ভিআর ব্যবহার করে নিমজ্জনকারী দুর্যোগ প্রস্তুতি সিমুলেশন',
      'vr.gettingStarted': 'মোবাইল ভিআর প্রশিক্ষণের সাথে শুরু করা',
      'vr.setupDesc': 'নিমজ্জনকারী প্রশিক্ষণের জন্য আপনার স্মার্টফোন এবং কার্ডবোর্ড ভিআর ভিউয়ার ব্যবহার করুন',
      'vr.smartphone': 'স্মার্টফোন',
      'vr.smartphoneDesc': 'জাইরোস্কোপ সেন্সর সহ Android 6.0+ বা iOS 10+',
      'vr.cardboardViewer': 'কার্ডবোর্ড ভিআর ভিউয়ার',
      'vr.cardboardDesc': 'DIY কার্ডবোর্ড বা Google Cardboard সামঞ্জস্যপূর্ণ ভিউয়ার',
      'vr.headphones': 'হেডফোন',
      'vr.headphonesDesc': 'উন্নত নিমজ্জনের জন্য ঐচ্ছিক ইয়ারফোন',
      'vr.downloadApp': 'ভিআর অ্যাপ ডাউনলোড করুন',
      'vr.setupGuide': 'সেটআপ গাইড',
      'vr.qrCodeDesc': 'DPRES VR অ্যাপ ডাউনলোড করতে আপনার ফোন দিয়ে এই QR কোড স্ক্যান করুন',
      'vr.comingSoon': 'শীঘ্রই আসছে',
      'vr.available': 'উপলব্ধ',
      'vr.beginner': 'শুরুকারী',
      'vr.intermediate': 'মধ্যবর্তী',
      'vr.advanced': 'উন্নত',
      'vr.startTraining': 'ভিআর প্রশিক্ষণ শুরু করুন',
      'vr.totalSessions': 'মোট ভিআর সেশন',
      'vr.completionRate': 'সম্পূর্ণতার হার',
      'vr.avgSessionTime': 'গড় সেশনের সময়',
      'vr.avgTime': '১৮ মিনিট',
      'vr.userRating': 'ব্যবহারকারী রেটিং',
      'vr.trainingPreview': 'ভিআর প্রশিক্ষণ পূর্বরূপ',
      'vr.previewDesc': 'আমাদের নিমজ্জনকারী প্রশিক্ষণ পরিবেশের একটি নমুনা অভিজ্ঞতা নিন',
      'vr.previewEnvironment': 'ভিআর পরিবেশের পূর্বরূপ',
      'vr.trainingEnvironmentAlt': 'ভিআর প্রশিক্ষণ পরিবেশ',
      'vr.earthquakeResponse': 'ভূমিকম্প প্রতিক্রিয়া',
      'vr.earthquakeDesc': 'বাস্তবসম্মত ভূমিকম্প পরিস্থিতির অভিজ্ঞতা নিন এবং নিরাপদ ভার্চুয়াল পরিবেশে যথাযথ ড্রপ, কভার এবং হোল্ড কৌশল শিখুন।',
      'vr.fireEmergency': 'অগ্নি জরুরি অবস্থা',
      'vr.fireDesc': 'অগ্নি জরুরি পরিস্থিতির মধ্য দিয়ে নেভিগেট করুন, নিকাশী রুট অনুশীলন করুন, এবং অগ্নি নিরাপত্তা সরঞ্জামের সঠিক ব্যবহার শিখুন।',
      'vr.floodResponse': 'বন্যা প্রতিক্রিয়া',
      'vr.floodDesc': 'বিভিন্ন বন্যার পরিস্থিতি এবং পরিবেশে বন্যা নিরাপত্তা প্রোটোকল এবং নিকাশী পদ্ধতি শিখুন।',
      'vr.cyclonePreparedness': 'ঘূর্ণিঝড় প্রস্তুতি',
      'vr.cycloneDesc': 'গুরুতর আবহাওয়া পরিস্থিতির অভিজ্ঞতা নিন এবং ঘূর্ণিঝড়ের সময় যথাযথ আশ্রয় এবং নিরাপত্তা ব্যবস্থা শিখুন।',
      'vr.duration15to20': '১৫-২০ মিনিট',
      'vr.duration12to18': '১২-১৮ মিনিট',
      'vr.duration20to25': '২০-২৫ মিনিট',
      'vr.duration18to22': '১৮-২২ মিনিট',
      
      // Common
      'common.loading': 'লোড হচ্ছে...',
      'common.error': 'ত্রুটি',
      'common.success': 'সফলতা',
      'common.cancel': 'বাতিল করুন',
      'common.save': 'সংরক্ষণ করুন',
      'common.edit': 'সম্পাদনা করুন',
      'common.delete': 'মুছে ফেলুন',
      'common.view': 'দেখুন',
      'common.close': 'বন্ধ করুন',
    }
  };
};